#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

tmp_dir=$TARGET_ROOT/tmp/spark-bench
mkdir -p $tmp_dir

SPARK_BENCH_DOWNLOAD_URL="https://github.com/CODAIT/spark-bench/releases/download/v99/spark-bench_2.3.0_0.4.0-RELEASE_99.tgz"

echo "Downloading SPARK"
spark_bench_file=$(basename "$SPARK_BENCH_DOWNLOAD_URL")
cached_tar="$DIB_IMAGE_CACHE/$spark_bench_file"
$TMP_HOOKS_PATH/bin/cache-url $SPARK_BENCH_DOWNLOAD_URL $cached_tar
sudo install -D -g root -o root -m 0755 $cached_tar $tmp_dir
echo "$SPARK_BENCH_DOWNLOAD_URL" > $tmp_dir/spark_bench_url.txt
